apiVersion: v1
kind: Namespace
metadata:
  name: medical-ai
  labels:
    name: medical-ai
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: medical-ai-quota
  namespace: medical-ai
spec:
  hard:
    requests.cpu: "50"
    requests.memory: 100Gi
    requests.nvidia.com/gpu: "10"
    persistentvolumeclaims: "20"
    pods: "50"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: medical-ai-limits
  namespace: medical-ai
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim