apiVersion: v1
kind: Secret
metadata:
  name: medical-ai-secrets
  namespace: medical-ai
type: Opaque
data:
  # 数据库连接信息 (base64编码)
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzMTIzQHBvc3RncmVzOjU0MzIvbWVkaWNhbF9haQ==
  DATABASE_PASSWORD: cG9zdGdyZXMxMjM=
  
  # Redis连接信息
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjM3OS8w
  REDIS_PASSWORD: ""
  
  # JWT密钥
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  
  # MinIO/S3配置
  MINIO_ENDPOINT: bWluaW86OTAwMA==
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbjEyMw==
  
  # RabbitMQ配置
  RABBITMQ_URL: YW1xcDovL2FkbWluOmFkbWluMTIzQHJhYmJpdG1xOjU2NzIv
  RABBITMQ_USERNAME: YWRtaW4=
  RABBITMQ_PASSWORD: YWRtaW4xMjM=
  
  # 邮件服务配置
  SMTP_HOST: c210cC5leGFtcGxlLmNvbQ==
  SMTP_PORT: NTg3
  SMTP_USERNAME: bm9yZXBseUBleGFtcGxlLmNvbQ==
  SMTP_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==
  
  # 第三方API密钥
  OPENAI_API_KEY: ""
  AZURE_API_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  
  # SSL证书 (如果需要)
  TLS_CERT: ""
  TLS_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: medical-ai
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ssl-certs
  namespace: medical-ai
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t